// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtAEdiZgT-G1prh4eXS-AYAF4kALd6uj0',
    appId: '1:248076275717:web:5f7cdf2f185e48b8d6cc6c',
    messagingSenderId: '248076275717',
    projectId: 'smhelmet-67',
    authDomain: 'smhelmet-67.firebaseapp.com',
    storageBucket: 'smhelmet-67.firebasestorage.app',
    measurementId: 'G-64BR14NLXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwBMhQRnegCVelu2dgDatX5_-mm7Op0k0',
    appId: '1:248076275717:android:187e717838d87f21d6cc6c',
    messagingSenderId: '248076275717',
    projectId: 'smhelmet-67',
    storageBucket: 'smhelmet-67.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtAEdiZgT-G1prh4eXS-AYAF4kALd6uj0',
    appId: '1:248076275717:web:0ec986cf8ecd42cad6cc6c',
    messagingSenderId: '248076275717',
    projectId: 'smhelmet-67',
    authDomain: 'smhelmet-67.firebaseapp.com',
    storageBucket: 'smhelmet-67.firebasestorage.app',
    measurementId: 'G-X92XQ8HDD3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDJ7tcX1YszAYkEK3E21KyebK9jJYFw9Q',
    appId: '1:248076275717:ios:ed8ef29a79570027d6cc6c',
    messagingSenderId: '248076275717',
    projectId: 'smhelmet-67',
    storageBucket: 'smhelmet-67.firebasestorage.app',
    iosClientId: '248076275717-gk7i9ehamqplh2j7do0c7qr0ardokafb.apps.googleusercontent.com',
    iosBundleId: 'helix.io',
  );

}